Add utils.h to dist_noinst_HEADERS
Fix the compiling error when runing packaging/RPM/makerpms.sh:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I./../include -I./include -Wall -W -Wshadow -Wstrict-prototypes -Wpointer-arith -Wcast-align -Wcast-qual -Wvla -Wno-unknown-warning-option -Wno-stringop-truncation -Wno-unused-parameter -Werror -Wwrite-strings -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -c sync.c -o libiscsipriv_la-sync.o >/dev/null 2>&1
scsi-lowlevel.c:59:10: fatal error: utils.h: No such file or directory
   59 | #include "utils.h"
      |          ^~~~~~~~~

Signed-off-by: Han Han <hhan@redhat.com>